### PR TITLE
url lib support no auth for https

### PR DESCRIPTION
**Pull request by guangtaopi**
access twitter api, the error will occur: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

so. the patch will support the parameter whether to enable verify context.

### CODE REVIEW

**Comment by boogheta** [comment]
Hi again,

As travis reports, there are still issues with this : the context argument does not exist in some Python versions (2.6, 3.2 and 3.3). It's true these are deprecated, although the code was working with them anyways and I'd like to keep this as such. Could you condition the use of context?

**Comment by RouxRC** [comment]
good news, since we dropped these versions for good now, it can now finally be merged seemlessly :)
I just rebased and pushed your commits with a minor change to master https://github.com/python-twitter-tools/twitter/commits/master

**Comment by RouxRC** [comment]
good news, since we dropped these versions for good now, it can now finally be merged seemlessly :)
I just rebased and pushed your commits with a minor change to master https://github.com/python-twitter-tools/twitter/commits/master

**Comment by boogheta** [comment]
-

**Pull request closed without merging**
