### PR TITLE
Using a ssl context object to avoid deprecation warnings in py3

### PR DESCRIPTION
**Pull request by Yomguithereal**

### CODE REVIEW

**Comment by hugovk** [comment]
Please could you add comments to say which bit is for Python 2 and which for 3?

That will make it easier to clean up the code when the time comes.

**Comment by Yomguithereal** [comment]
> Please could you add comments to say which bit is for Python 2 and which for 3?

The code I wrote works the same in py2 and py3 as far as I know so nothing to clean up when the time comes (to kill py2 I suppose?). It's just that the earlier PR was triggering deprecation warning on py >= 3.6. Now it does not.

**Comment by boogheta** [comment]
I'm the one who sollicitated the PR to @Yomguithereal following the previous one.
This solves an issue we met while using the lib on recent Mac where python could not find on its own where the certifs relies on the OS. This makes me wonder actually whether we should add to the matrix some tests under macos/windows as well, although that's already a lot of tweets sent whenever tests are run so not sure. What do you think @hugovk?

**Comment by hugovk** [comment]
I think it's a good idea to test at least one on Windows and macOS. We don't necessarily need to add them to the full matrix to get the benefit.

We currently have:

```yml
            "2.7",
            "3.6",
            "3.7",
            "3.8",
            "3.9",
            "3.10",
            "3.11-dev",
            "pypy2.7",
```

We could switch out one of these middle versions to run on Windows instead of Ubuntu, and another to run on macOS.

In fact, we could remove some of those middle Ubuntu ones anyway, some projects only test on lower and upper bounds. So for example:

```diff
            "2.7",
            "3.6",
-           "3.7",
-           "3.8",
-           "3.9",
            "3.10",
            "3.11-dev",
            "pypy2.7",
```

Also Python 3.6 has been EOL since last year (2021-12-23) so that could be dropped. (Plus I still recommend EOL 2.7 being dropped (2020-01-01) ;)

**Comment by boogheta** [comment]
I like the idea to test some versions with mac and windows, for instance we could remove 3.7, and replace 3.8 with windows and 3.9 with mac ?
I know for 2.7, but I kinda like that the code is robust enough that it still supports it so far and I would be in favor of keeping it unless it becomes a maintenance charge, but that's only my opinion :)

**Comment by hugovk** [comment]
Sounds good, I'll create a PR. Fine with me if you'd like to keep 2.7 longer. How about 3.6?

**Comment by hugovk** [comment]
Please see PR https://github.com/python-twitter-tools/twitter/pull/453

**Pull request merged**
